post http://localhost:3002/api/users/login
content-type: application/json

{
    "data":{
        "login": "komkim",
        "password": "pwd123"
    }
}

###


post http://localhost:3002/api/customers/getcustomers
content-type: application/json

{
    "userId": "3",
    "auth_id": "946fb12655f3cd72ec5dc6cfaef704f9464eb2c5c4aecbbe3cf2d74729a82dd0"
}

###
post http://localhost:3002/api/customers/getcustomer/1
content-type: application/json

{
    "userId": "3",
    "auth_id": "12df02476cdb0764a629a16bf48a1a8266380773c757bb0a7f605f31d09ab4dc"
}
###

post http://localhost:3002/api/customers/updatecustomer/1
content-type: application/json

{
    "userId": "32",
    "auth_id": "122df02476cdb0764a629a16bf48a1a8266380773c757bb0a7f605f31d09ab4dc",
    "data": {
        "firstname" : "test"
    }
}
###

post http://localhost:3002/api/customers/deletecustomer/1
content-type: application/json

{
    "userId": "3",
    "auth_id": "12df02476cdb0764a629a16bf48a1a8266380773c757bb0a7f605f31d09ab4dc"    
}

###

post http://localhost:3002/api/customers/createcustomer
content-type: application/json

{
    "userId": "3",
    "auth_id": "12df02476cdb0764a629a16bf48a1a8266380773c757bb0a7f605f31d09ab4dc"    ,
    "data" : {
        "phone" : "test",
        "firstname" : "test"
    }
}