post http://localhost:3002/api/login
content-type: application/json

{
    "data":{
        "login": "komkim",
        "password": "pwd123"
    }
}

###

post http://localhost:3002/api/logout
content-type: application/json

{}
###
post http://localhost:3002/api/contracts_new/getcontracts
content-type: application/json

{    
    "data" :{        
       "user_id":3
    },
    "userId": "3"
}

###
post http://localhost:3002/api/contracts_new/getcontract/3
content-type: application/json

{    
    "userId": "3"
}   
###
put http://localhost:3002/api/contracts_new/updatecontracts/3
content-type: application/json

{   
    "userId": "3",
    "data": {
        "contract_number" : 6665
    }
}

###
put http://localhost:3002/api/contracts_new/createcontract
content-type: application/json

{
    "userId": "3",    
    "data" : {
        "contract_number" : 45612,        
        "address":"test",
        "customer":3
    }
}

###

DELETE  http://localhost:3002/api/contracts_new/deletecontract/30
content-type: application/json

{
    "userId": "3"
}